[package]
name = "pallet-manta-dap"
version = "3.0.0"
authors = ["Manta Network <contact@manta.network>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/Manta-Network/pallet-manta-dap"
description = "Manta DAP scheme"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Substrate dependencies
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-inherents = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-version = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
frame-executive = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-state-machine = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-trie = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
sp-externalities = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1", optional = true }

# Other Dependencies
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"]}
serde = { version = "1.0.101", optional = true, features = ["derive"] }
hash-db = { version = "0.15.2", default-features = false }
memory-db = { version = "0.26.0", default-features = false }
trie-db = { version = "0.22.0", default-features = false }

rand = { version = "0.7", default-features = false }
rand_core =  { version = "0.5", default-features = false }
rand_chacha = { version = "0.2.2", default-features = false }
ark-ed-on-bls12-381 = { version = "0.1.0", git = "https://github.com/arkworks-rs/curves/", default-features = false, features = [ "r1cs" ] }
ark-bls12-381 = { version = "0.1.0", git = "https://github.com/arkworks-rs/curves/", default-features = false, features = [ "curve" ] }
ark-crypto-primitives = { version = "0.1.0", git = "https://github.com/arkworks-rs/crypto-primitives.git", branch = "main", default-features = false, features = [ "r1cs" ] }
ark-ff = { git = "https://github.com/arkworks-rs/algebra", default-features = false }
ark-ec = { git = "https://github.com/arkworks-rs/algebra", default-features = false }
ark-std = { git = "https://github.com/arkworks-rs/utils", default-features = false }
ark-groth16 = { git = "https://github.com/arkworks-rs/groth16", default-features = false, features = [ "r1cs" ] }
ark-r1cs-std = { git = "https://github.com/arkworks-rs/r1cs-std", default-features = false }
ark-relations = { git = "https://github.com/arkworks-rs/snark", default-features = false }
ark-serialize = { git = "https://github.com/arkworks-rs/algebra", default-features = false, features = [ "derive" ] }

hkdf = { version = "0.10", default-features = false }
sha2 = { version = "0.9.3", default-features = false }
aes = { version = "0.6.0", default-features = false }
x25519-dalek = { version = "1.1.0", default-features = false, features = [ "u64_backend" ]}
generic-array = { version = "0.14.0", default-features = false }
blake2 = { version = "0.9.1", default-features = false }

data-encoding = { version = "2.3.2", default-features = false, features = [ "alloc" ] }

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-v1" }

[dev-dependencies]



# benchmarking 
bencher = "0.1.5"
criterion = "0.2.11"

[[bench]]
name = "manta_bench"
harness = false

[features]
default = ["std"]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-system/runtime-benchmarks"
	]
std = [
	"serde",
	"codec/std",
	"sp-core/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"frame-benchmarking/std",
]
